Add option to disable magic comment completions
TheRealSyler/vscode-sass-indented pull request #120
Opened 2023-03-07 08:26 UTC by hibiyasleep

2023-03-07 12:10 UTC, TheRealSyler commented
@hibiyasleep thanks for creating the pr, there are two small issue with the code (see code review), i will merge the pr once they are fixed.

2023-03-08 08:42 UTC, hibiyasleep commented
Thank you, but I can't see any comments, maybe they're under 'Pending' state?

2023-03-08 08:49 UTC, TheRealSyler requested changes

2023-03-08 08:50 UTC, TheRealSyler commented
@hibiyasleep ups, i forgot to request the changes, should be visible now.

2023-03-08 09:21 UTC, hibiyasleep commented on src/autocomplete/autocomplete.ts
> +    const disableCommentCompletion: boolean = config.get('sass.disableUnitCompletion');
oops, fixed!

2023-03-08 17:53 UTC, merged