Updated CSS property autocompletion and other misc changes
TheRealSyler/vscode-sass-indented pull request #99
Opened 2022-06-20 15:06 UTC by Mitchman215

@TheRealSyler 
Addresses #98.
I added a package script `update-css` that pulls css data from [@vscode/web-custom-data](https://www.npmjs.com/package/@vscode/web-custom-data), so hopefully this will make it easy to keep the data up to date. Currently, it only uses the properties data, but it also pulls in pseudo-elements/classes and at-rules, so that could be used in the future too. I also added a `useNewData` field to the "autcomplete.utility.ts" file that can revert to using the old css data if you want.
One last thing: I updated the dependencies in order to get the project to run for me and I added eslint for some linting. If you want me to change anything, just let me know.

2022-06-20 15:08 UTC, Mitchman215 commented
Sorry this took a while! I have been preoccupied with other things and am still getting used to typescript and vscode's API. That being said, I enjoyed working on this and would be interested in working more on this project. I have a few ideas that I can talk to you about if you are interested (I'm not sure how much you are still working on this project).
I noticed the "sass-lsp" branch, is that a language server implementation?

2022-06-20 16:06 UTC, TheRealSyler requested changes
Looks good, just address the comments i made and if you decide to remove the `useNewData` variable without replacing it by an extension setting also remove the old code and the old data that is not being used.

Other than that the pr should be ready to merge.

2022-06-20 16:06 UTC, TheRealSyler commented on src/autocomplete/cssLanguageTypes.ts
> +// /*---------------------------------------------------------------------------------------------
Im not sure what this file is supposed to do, i think you can just delete it.

2022-06-20 16:14 UTC, TheRealSyler commented
no worries, we all have stuff to do, you have all the time in the world.

feel free to add any feature you want, if i don't think it fits the extension you can just copy and paste it into a new extension like i did with my [sass-next](https://github.com/TheRealSyler/vscode-sass-next) extension.

im no longer working on the sass-lsp branch(or any new features) and i don't remember what i wanted to do with it.

thanks for taking the time to contribute.

2022-06-23 03:47 UTC, Mitchman215 commented
@TheRealSyler 
Thanks for the feedback, I fixed all the things you made comments about.
I also made autocomplete use the new pseudo class/elements data.
Let me know if theres anything else I need to address before this is merged.

2022-06-23 07:50 UTC, TheRealSyler requested changes
There are a few small changes, i think either you or me can commit them directly via github, not sure how the feature works i never used it, if i can do it ill just merge the pr, thanks again for taking the time to contribute.

2022-06-23 07:50 UTC, TheRealSyler commented on src/autocomplete/autocomplete.ts
> +    // console.log({ completions });
```suggestion
```

2022-06-23 07:50 UTC, TheRealSyler commented on src/autocomplete/autocomplete.utility.ts
> +      // TODO: ideally, trigger intellisense to autosuggest possible values of property
```suggestion
```

2022-06-23 07:50 UTC, TheRealSyler commented on src/autocomplete/autocomplete.utility.ts
> +   *  Assumes that the parentheses are in the names if the enttity is indeed a function.
```suggestion
   *  Assumes that the parentheses are in the names if the entity is indeed a function.
```

2022-06-23 07:50 UTC, TheRealSyler commented on src/autocomplete/autocomplete.utility.ts
>    }
```suggestion
  static findPropertySchema(property: string) {
    return cssData.properties.find(prop => prop.name === property);
  }
```

2022-06-23 07:50 UTC, TheRealSyler commented on src/scripts/generateCssData.ts
> +	`import { CSSDataV1 } from '../../autocomplete.interfaces';`,
```suggestion
	`import { ${DATA_TYPE} } from '../../autocomplete.interfaces';`,
```

2022-06-23 07:50 UTC, TheRealSyler commented on tsconfig.json
> +    "lib": ["es6", "ES2018"],  // ES2018 needed for regex groups support
```suggestion
    "lib": ["es6", "ES2018"],
```

2022-06-23 07:58 UTC, TheRealSyler commented on src/autocomplete/autocomplete.utility.ts
>    }
```suggestion
  static findPropertySchema(property: string) {
    return cssData.properties.find(prop => prop.name === property);
  }
```

2022-06-23 08:03 UTC, merged